name: CI/CD Test

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  tests:
    name: Running unit tests
    runs-on: ubuntu-latest
    steps:
    # checkout code
    - uses: actions/checkout@v1
    # setup java 11
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
        cache: maven
    # run tests
    - run: mvn --batch-mode test
  qa:
    name: Running integration tests
    needs: tests
    runs-on: ubuntu-latest
    steps:
    # checkout code
    - uses: actions/checkout@v1
    # setup java 11
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
        cache: maven
    # build and run integration tests
    - run: mvn --batch-mode --update-snapshots verify
  build:
    name: Build image to GCP image registry
    needs: qa
    runs-on: ubunt-latest
    steps:
    # checkout code
    - uses: actions/checkout@v1
    # auth to GCP
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    # auth docker for GCP
    - run: |
        gcloud auth configure-docker
    # build image
    - run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/demo:latest .
    # push image to GCP Container Registry
    - run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/demo:latest .
  deploy:
    name: Deploy image to GCP Cloud Run
    needs: build
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v1
      # auth to GCP
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      # deploy image to GCP Cloud Run
      - run: |
          gcloud run deploy demo \
          --region europe-west1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/demo \
          --plaform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}


